# Generated by Django 5.2.6 on 2025-09-23 23:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('boots', 'Football Boots'), ('training', 'Training Gear'), ('accessories', 'Accessories'), ('ball', 'Football'), ('lifestyle', 'Lifestyle'), ('collectibles', 'Collectibles'), ('others', 'Others')], default='jersey', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('sold', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
