# Generated by Django 5.2.6 on 2025-09-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('boots', 'Football Boots'), ('training', 'Training Gear'), ('accessories', 'Accessories'), ('ball', 'Football'), ('lifestyle', 'Lifestyle'), ('collectibles', 'Collectibles')], default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
