# Generated by Django 5.2.6 on 2025-09-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('boots', 'Football Boots'), ('training', 'Training Gear'), ('accessories', 'Accessories'), ('ball', 'Football'), ('lifestyle', 'Lifestyle'), ('collectibles', 'Collectibles'), ('others', 'Others')], default='jersey', max_length=20),
        ),
    ]
